
dubbo:
  registry:
    address: localhost:2181
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nt?serverTimezone=GMT
    username: root
    password: nt123
